javadoc -d doc src/tp/pr2/*.java src/tp/pr2/control/*.java src/tp/pr2/control/commands/*.java src/tp/pr2/logic/*.java src/tp/pr2/logic/util/*.java src/tp/pr2/logic/multigames/*.java
set /p= Press "ENTER" to continue...
